# Generated by Django 4.1 on 2022-08-19 00:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('icao24', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('callsign', models.CharField(blank=True, max_length=40, null=True)),
                ('origin_country', models.CharField(max_length=100)),
                ('time_position', models.IntegerField(blank=True, null=True)),
                ('last_contact', models.IntegerField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('baro_altitude', models.FloatField(blank=True, null=True)),
                ('on_ground', models.BooleanField()),
                ('velocity', models.FloatField(blank=True, null=True)),
                ('true_track', models.FloatField(blank=True, null=True)),
                ('vertical_rate', models.FloatField(blank=True, null=True)),
                ('sensors', models.IntegerField(blank=True, null=True)),
                ('geo_altitude', models.FloatField(blank=True, null=True)),
                ('squawk', models.CharField(blank=True, max_length=40, null=True)),
                ('spi', models.BooleanField()),
                ('position_source', models.IntegerField()),
                ('users', models.ManyToManyField(related_name='favorite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
